// Generated by rstantools.  Do not edit by hand.

/*
    rstanmsm is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rstanmsm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rstanmsm.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_msm_constant_continuous_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_msm_constant_continuous");
    reader.add_event(203, 201, "end", "model_msm_constant_continuous");
    return reader;
}
#include <stan_meta_header.hpp>
class model_msm_constant_continuous : public prob_grad {
private:
        int N;
        int T;
        int NT;
        std::vector<std::vector<int> > startstop;
        int K;
        int Mx_d;
        int Mx_e;
        matrix_d x_d;
        matrix_d x_e;
        vector_d y;
        std::vector<int> has_intercept;
        int shared_TP;
        int shared_S;
        std::vector<int> order_x_e;
        int Mx_d_;
        int Mx_e_;
        matrix_d x_d_;
        matrix_d x_e_;
        int N_tp;
        int N_s;
        int Mx_e_un;
        int Mx_e_ord;
public:
    model_msm_constant_continuous(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_msm_constant_continuous(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_msm_constant_continuous_namespace::model_msm_constant_continuous";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            check_greater_or_equal(function__, "N", N, 1);
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "T", "int", context__.to_vec());
            T = int(0);
            vals_i__ = context__.vals_i("T");
            pos__ = 0;
            T = vals_i__[pos__++];
            check_greater_or_equal(function__, "T", T, 2);
            current_statement_begin__ = 5;
            context__.validate_dims("data initialization", "NT", "int", context__.to_vec());
            NT = int(0);
            vals_i__ = context__.vals_i("NT");
            pos__ = 0;
            NT = vals_i__[pos__++];
            check_greater_or_equal(function__, "NT", NT, (N * T));
            current_statement_begin__ = 6;
            validate_non_negative_index("startstop", "N", N);
            validate_non_negative_index("startstop", "2", 2);
            context__.validate_dims("data initialization", "startstop", "int", context__.to_vec(N,2));
            startstop = std::vector<std::vector<int> >(N, std::vector<int>(2, int(0)));
            vals_i__ = context__.vals_i("startstop");
            pos__ = 0;
            size_t startstop_k_0_max__ = N;
            size_t startstop_k_1_max__ = 2;
            for (size_t k_1__ = 0; k_1__ < startstop_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < startstop_k_0_max__; ++k_0__) {
                    startstop[k_0__][k_1__] = vals_i__[pos__++];
                }
            }
            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 2);
            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "Mx_d", "int", context__.to_vec());
            Mx_d = int(0);
            vals_i__ = context__.vals_i("Mx_d");
            pos__ = 0;
            Mx_d = vals_i__[pos__++];
            check_greater_or_equal(function__, "Mx_d", Mx_d, 0);
            current_statement_begin__ = 11;
            context__.validate_dims("data initialization", "Mx_e", "int", context__.to_vec());
            Mx_e = int(0);
            vals_i__ = context__.vals_i("Mx_e");
            pos__ = 0;
            Mx_e = vals_i__[pos__++];
            check_greater_or_equal(function__, "Mx_e", Mx_e, 0);
            current_statement_begin__ = 14;
            validate_non_negative_index("x_d", "NT", NT);
            validate_non_negative_index("x_d", "Mx_d", Mx_d);
            context__.validate_dims("data initialization", "x_d", "matrix_d", context__.to_vec(NT,Mx_d));
            x_d = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(NT, Mx_d);
            vals_r__ = context__.vals_r("x_d");
            pos__ = 0;
            size_t x_d_j_2_max__ = Mx_d;
            size_t x_d_j_1_max__ = NT;
            for (size_t j_2__ = 0; j_2__ < x_d_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_d_j_1_max__; ++j_1__) {
                    x_d(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 15;
            validate_non_negative_index("x_e", "NT", NT);
            validate_non_negative_index("x_e", "Mx_e", Mx_e);
            context__.validate_dims("data initialization", "x_e", "matrix_d", context__.to_vec(NT,Mx_e));
            x_e = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(NT, Mx_e);
            vals_r__ = context__.vals_r("x_e");
            pos__ = 0;
            size_t x_e_j_2_max__ = Mx_e;
            size_t x_e_j_1_max__ = NT;
            for (size_t j_2__ = 0; j_2__ < x_e_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_e_j_1_max__; ++j_1__) {
                    x_e(j_1__, j_2__) = vals_r__[pos__++];
                }
            }
            current_statement_begin__ = 18;
            validate_non_negative_index("y", "NT", NT);
            context__.validate_dims("data initialization", "y", "vector_d", context__.to_vec(NT));
            y = Eigen::Matrix<double, Eigen::Dynamic, 1>(NT);
            vals_r__ = context__.vals_r("y");
            pos__ = 0;
            size_t y_j_1_max__ = NT;
            for (size_t j_1__ = 0; j_1__ < y_j_1_max__; ++j_1__) {
                y(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 21;
            validate_non_negative_index("has_intercept", "5", 5);
            context__.validate_dims("data initialization", "has_intercept", "int", context__.to_vec(5));
            has_intercept = std::vector<int>(5, int(0));
            vals_i__ = context__.vals_i("has_intercept");
            pos__ = 0;
            size_t has_intercept_k_0_max__ = 5;
            for (size_t k_0__ = 0; k_0__ < has_intercept_k_0_max__; ++k_0__) {
                has_intercept[k_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 24;
            context__.validate_dims("data initialization", "shared_TP", "int", context__.to_vec());
            shared_TP = int(0);
            vals_i__ = context__.vals_i("shared_TP");
            pos__ = 0;
            shared_TP = vals_i__[pos__++];
            current_statement_begin__ = 25;
            context__.validate_dims("data initialization", "shared_S", "int", context__.to_vec());
            shared_S = int(0);
            vals_i__ = context__.vals_i("shared_S");
            pos__ = 0;
            shared_S = vals_i__[pos__++];
            current_statement_begin__ = 28;
            validate_non_negative_index("order_x_e", "(Mx_e + get_base1(has_intercept, 2, \"has_intercept\", 1))", (Mx_e + get_base1(has_intercept, 2, "has_intercept", 1)));
            context__.validate_dims("data initialization", "order_x_e", "int", context__.to_vec((Mx_e + get_base1(has_intercept, 2, "has_intercept", 1))));
            order_x_e = std::vector<int>((Mx_e + get_base1(has_intercept, 2, "has_intercept", 1)), int(0));
            vals_i__ = context__.vals_i("order_x_e");
            pos__ = 0;
            size_t order_x_e_k_0_max__ = (Mx_e + get_base1(has_intercept, 2, "has_intercept", 1));
            for (size_t k_0__ = 0; k_0__ < order_x_e_k_0_max__; ++k_0__) {
                order_x_e[k_0__] = vals_i__[pos__++];
            }
            // initialize transformed data variables
            current_statement_begin__ = 34;
            Mx_d_ = int(0);
            stan::math::fill(Mx_d_, std::numeric_limits<int>::min());
            stan::math::assign(Mx_d_,(get_base1(has_intercept, 1, "has_intercept", 1) ? (Mx_d + get_base1(has_intercept, 1, "has_intercept", 1)) : (logical_eq(Mx_d, 0) ? 1 : Mx_d ) ));
            current_statement_begin__ = 35;
            Mx_e_ = int(0);
            stan::math::fill(Mx_e_, std::numeric_limits<int>::min());
            stan::math::assign(Mx_e_,(get_base1(has_intercept, 2, "has_intercept", 1) ? (Mx_e + get_base1(has_intercept, 2, "has_intercept", 1)) : (logical_eq(Mx_e, 0) ? 1 : Mx_e ) ));
            current_statement_begin__ = 36;
            validate_non_negative_index("x_d_", "NT", NT);
            validate_non_negative_index("x_d_", "Mx_d_", Mx_d_);
            x_d_ = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(NT, Mx_d_);
            stan::math::fill(x_d_, DUMMY_VAR__);
            stan::math::assign(x_d_,(get_base1(has_intercept, 1, "has_intercept", 1) ? stan::math::promote_scalar<double>(append_col(rep_vector(1.0, NT), x_d)) : stan::math::promote_scalar<double>((logical_eq(Mx_d, 0) ? stan::math::promote_scalar<double>(rep_matrix(0.0, NT, 1)) : stan::math::promote_scalar<double>(x_d) )) ));
            current_statement_begin__ = 38;
            validate_non_negative_index("x_e_", "NT", NT);
            validate_non_negative_index("x_e_", "Mx_e_", Mx_e_);
            x_e_ = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(NT, Mx_e_);
            stan::math::fill(x_e_, DUMMY_VAR__);
            stan::math::assign(x_e_,(get_base1(has_intercept, 2, "has_intercept", 1) ? stan::math::promote_scalar<double>(append_col(rep_vector(1.0, NT), x_e)) : stan::math::promote_scalar<double>((logical_eq(Mx_e, 0) ? stan::math::promote_scalar<double>(rep_matrix(0.0, NT, 1)) : stan::math::promote_scalar<double>(x_e) )) ));
            current_statement_begin__ = 42;
            N_tp = int(0);
            stan::math::fill(N_tp, std::numeric_limits<int>::min());
            stan::math::assign(N_tp,(shared_TP ? 1 : N ));
            current_statement_begin__ = 43;
            N_s = int(0);
            stan::math::fill(N_s, std::numeric_limits<int>::min());
            stan::math::assign(N_s,(shared_S ? 1 : N ));
            current_statement_begin__ = 46;
            Mx_e_un = int(0);
            stan::math::fill(Mx_e_un, std::numeric_limits<int>::min());
            stan::math::assign(Mx_e_un,(Mx_e_ - sum(order_x_e)));
            current_statement_begin__ = 47;
            Mx_e_ord = int(0);
            stan::math::fill(Mx_e_ord, std::numeric_limits<int>::min());
            stan::math::assign(Mx_e_ord,sum(order_x_e));
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 52;
            validate_non_negative_index("pi1", "K", K);
            validate_non_negative_index("pi1", "N_s", N_s);
            num_params_r__ += ((K - 1) * N_s);
            current_statement_begin__ = 53;
            validate_non_negative_index("A", "K", K);
            validate_non_negative_index("A", "N_tp", N_tp);
            validate_non_negative_index("A", "K", K);
            num_params_r__ += (((K - 1) * N_tp) * K);
            current_statement_begin__ = 56;
            validate_non_negative_index("phi", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 57;
            validate_non_negative_index("alpha", "Mx_d_", Mx_d_);
            num_params_r__ += Mx_d_;
            current_statement_begin__ = 59;
            validate_non_negative_index("beta_un", "K", K);
            validate_non_negative_index("beta_un", "Mx_e_un", Mx_e_un);
            num_params_r__ += (K * Mx_e_un);
            current_statement_begin__ = 60;
            validate_non_negative_index("beta_ord", "K", K);
            validate_non_negative_index("beta_ord", "Mx_e_ord", Mx_e_ord);
            num_params_r__ += (K * Mx_e_ord);
            current_statement_begin__ = 61;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_msm_constant_continuous() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 52;
        if (!(context__.contains_r("pi1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable pi1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("pi1");
        pos__ = 0U;
        validate_non_negative_index("pi1", "K", K);
        validate_non_negative_index("pi1", "N_s", N_s);
        context__.validate_dims("parameter initialization", "pi1", "vector_d", context__.to_vec(N_s,K));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > pi1(N_s, Eigen::Matrix<double, Eigen::Dynamic, 1>(K));
        size_t pi1_j_1_max__ = K;
        size_t pi1_k_0_max__ = N_s;
        for (size_t j_1__ = 0; j_1__ < pi1_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < pi1_k_0_max__; ++k_0__) {
                pi1[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t pi1_i_0_max__ = N_s;
        for (size_t i_0__ = 0; i_0__ < pi1_i_0_max__; ++i_0__) {
            try {
                writer__.simplex_unconstrain(pi1[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable pi1: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 53;
        if (!(context__.contains_r("A")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable A missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("A");
        pos__ = 0U;
        validate_non_negative_index("A", "K", K);
        validate_non_negative_index("A", "N_tp", N_tp);
        validate_non_negative_index("A", "K", K);
        context__.validate_dims("parameter initialization", "A", "vector_d", context__.to_vec(N_tp,K,K));
        std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > > A(N_tp, std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(K, Eigen::Matrix<double, Eigen::Dynamic, 1>(K)));
        size_t A_j_1_max__ = K;
        size_t A_k_0_max__ = N_tp;
        size_t A_k_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < A_j_1_max__; ++j_1__) {
            for (size_t k_1__ = 0; k_1__ < A_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < A_k_0_max__; ++k_0__) {
                    A[k_0__][k_1__](j_1__) = vals_r__[pos__++];
                }
            }
        }
        size_t A_i_0_max__ = N_tp;
        size_t A_i_1_max__ = K;
        for (size_t i_0__ = 0; i_0__ < A_i_0_max__; ++i_0__) {
            for (size_t i_1__ = 0; i_1__ < A_i_1_max__; ++i_1__) {
                try {
                    writer__.simplex_unconstrain(A[i_0__][i_1__]);
                } catch (const std::exception& e) {
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable A: ") + e.what()), current_statement_begin__, prog_reader__());
                }
            }
        }
        current_statement_begin__ = 56;
        if (!(context__.contains_r("phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("phi");
        pos__ = 0U;
        validate_non_negative_index("phi", "K", K);
        context__.validate_dims("parameter initialization", "phi", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> phi(K);
        size_t phi_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
            phi(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.ordered_unconstrain(phi);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable phi: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 57;
        if (!(context__.contains_r("alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("alpha");
        pos__ = 0U;
        validate_non_negative_index("alpha", "Mx_d_", Mx_d_);
        context__.validate_dims("parameter initialization", "alpha", "vector_d", context__.to_vec(Mx_d_));
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha(Mx_d_);
        size_t alpha_j_1_max__ = Mx_d_;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            alpha(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 59;
        if (!(context__.contains_r("beta_un")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_un missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_un");
        pos__ = 0U;
        validate_non_negative_index("beta_un", "K", K);
        validate_non_negative_index("beta_un", "Mx_e_un", Mx_e_un);
        context__.validate_dims("parameter initialization", "beta_un", "vector_d", context__.to_vec(Mx_e_un,K));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > beta_un(Mx_e_un, Eigen::Matrix<double, Eigen::Dynamic, 1>(K));
        size_t beta_un_j_1_max__ = K;
        size_t beta_un_k_0_max__ = Mx_e_un;
        for (size_t j_1__ = 0; j_1__ < beta_un_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_un_k_0_max__; ++k_0__) {
                beta_un[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t beta_un_i_0_max__ = Mx_e_un;
        for (size_t i_0__ = 0; i_0__ < beta_un_i_0_max__; ++i_0__) {
            try {
                writer__.vector_unconstrain(beta_un[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_un: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 60;
        if (!(context__.contains_r("beta_ord")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta_ord missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta_ord");
        pos__ = 0U;
        validate_non_negative_index("beta_ord", "K", K);
        validate_non_negative_index("beta_ord", "Mx_e_ord", Mx_e_ord);
        context__.validate_dims("parameter initialization", "beta_ord", "vector_d", context__.to_vec(Mx_e_ord,K));
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > beta_ord(Mx_e_ord, Eigen::Matrix<double, Eigen::Dynamic, 1>(K));
        size_t beta_ord_j_1_max__ = K;
        size_t beta_ord_k_0_max__ = Mx_e_ord;
        for (size_t j_1__ = 0; j_1__ < beta_ord_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_ord_k_0_max__; ++k_0__) {
                beta_ord[k_0__](j_1__) = vals_r__[pos__++];
            }
        }
        size_t beta_ord_i_0_max__ = Mx_e_ord;
        for (size_t i_0__ = 0; i_0__ < beta_ord_i_0_max__; ++i_0__) {
            try {
                writer__.ordered_unconstrain(beta_ord[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta_ord: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 61;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 52;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > pi1;
            size_t pi1_d_0_max__ = N_s;
            pi1.reserve(pi1_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < pi1_d_0_max__; ++d_0__) {
                if (jacobian__)
                    pi1.push_back(in__.simplex_constrain(K, lp__));
                else
                    pi1.push_back(in__.simplex_constrain(K));
            }
            current_statement_begin__ = 53;
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > > A;
            size_t A_d_0_max__ = N_tp;
            size_t A_d_1_max__ = K;
            A.resize(A_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < A_d_0_max__; ++d_0__) {
                A[d_0__].reserve(A_d_1_max__);
                for (size_t d_1__ = 0; d_1__ < A_d_1_max__; ++d_1__) {
                    if (jacobian__)
                        A[d_0__].push_back(in__.simplex_constrain(K, lp__));
                    else
                        A[d_0__].push_back(in__.simplex_constrain(K));
                }
            }
            current_statement_begin__ = 56;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> phi;
            (void) phi;  // dummy to suppress unused var warning
            if (jacobian__)
                phi = in__.ordered_constrain(K, lp__);
            else
                phi = in__.ordered_constrain(K);
            current_statement_begin__ = 57;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> alpha;
            (void) alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                alpha = in__.vector_constrain(Mx_d_, lp__);
            else
                alpha = in__.vector_constrain(Mx_d_);
            current_statement_begin__ = 59;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > beta_un;
            size_t beta_un_d_0_max__ = Mx_e_un;
            beta_un.reserve(beta_un_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < beta_un_d_0_max__; ++d_0__) {
                if (jacobian__)
                    beta_un.push_back(in__.vector_constrain(K, lp__));
                else
                    beta_un.push_back(in__.vector_constrain(K));
            }
            current_statement_begin__ = 60;
            std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > beta_ord;
            size_t beta_ord_d_0_max__ = Mx_e_ord;
            beta_ord.reserve(beta_ord_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < beta_ord_d_0_max__; ++d_0__) {
                if (jacobian__)
                    beta_ord.push_back(in__.ordered_constrain(K, lp__));
                else
                    beta_ord.push_back(in__.ordered_constrain(K));
            }
            current_statement_begin__ = 61;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 65;
            validate_non_negative_index("beta", "Mx_e_", Mx_e_);
            validate_non_negative_index("beta", "K", K);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, Eigen::Dynamic> beta(Mx_e_, K);
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            current_statement_begin__ = 66;
            validate_non_negative_index("logalpha", "K", K);
            validate_non_negative_index("logalpha", "T", T);
            validate_non_negative_index("logalpha", "N_s", N_s);
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> > > logalpha(T, std::vector<Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> >(N_s, Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1>(K)));
            stan::math::initialize(logalpha, DUMMY_VAR__);
            stan::math::fill(logalpha, DUMMY_VAR__);
            // transformed parameters block statements
            {
            current_statement_begin__ = 69;
            int count_ordered(0);
            (void) count_ordered;  // dummy to suppress unused var warning
            stan::math::fill(count_ordered, std::numeric_limits<int>::min());
            stan::math::assign(count_ordered,1);
            current_statement_begin__ = 70;
            int count_unordered(0);
            (void) count_unordered;  // dummy to suppress unused var warning
            stan::math::fill(count_unordered, std::numeric_limits<int>::min());
            stan::math::assign(count_unordered,1);
            current_statement_begin__ = 71;
            for (int m = 1; m <= Mx_e_; ++m) {
                current_statement_begin__ = 72;
                if (as_bool(get_base1(order_x_e, m, "order_x_e", 1))) {
                    current_statement_begin__ = 73;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(m), stan::model::nil_index_list()), 
                                transpose(get_base1(beta_ord, count_ordered, "beta_ord", 1)), 
                                "assigning variable beta");
                    current_statement_begin__ = 73;
                    stan::math::assign(count_ordered, (count_ordered + 1));
                } else {
                    current_statement_begin__ = 75;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(m), stan::model::nil_index_list()), 
                                transpose(get_base1(beta_un, count_unordered, "beta_un", 1)), 
                                "assigning variable beta");
                    current_statement_begin__ = 75;
                    stan::math::assign(count_unordered, (count_unordered + 1));
                }
            }
            }
            current_statement_begin__ = 79;
            if (as_bool(logical_eq(shared_S, 0))) {
                current_statement_begin__ = 86;
                for (int nn = 1; nn <= N; ++nn) {
                    {
                    current_statement_begin__ = 87;
                    int nn_(0);
                    (void) nn_;  // dummy to suppress unused var warning
                    stan::math::fill(nn_, std::numeric_limits<int>::min());
                    stan::math::assign(nn_,(shared_TP ? 1 : nn ));
                    current_statement_begin__ = 88;
                    for (int j = 1; j <= K; ++j) {
                        current_statement_begin__ = 89;
                        stan::model::assign(logalpha, 
                                    stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(nn), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), 
                                    (stan::math::log(get_base1(get_base1(pi1, nn, "pi1", 1), j, "pi1", 2)) + normal_log(get_base1(y, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "y", 1), (multiply(get_base1(x_d_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_d_", 1), alpha) + multiply(get_base1(x_e_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)), 
                                    "assigning variable logalpha");
                    }
                    current_statement_begin__ = 93;
                    for (int t = 2; t <= T; ++t) {
                        current_statement_begin__ = 94;
                        for (int j = 1; j <= K; ++j) {
                            {
                            current_statement_begin__ = 95;
                            validate_non_negative_index("accumulator", "K", K);
                            std::vector<local_scalar_t__  > accumulator(K, local_scalar_t__(DUMMY_VAR__));
                            stan::math::initialize(accumulator, DUMMY_VAR__);
                            stan::math::fill(accumulator, DUMMY_VAR__);
                            current_statement_begin__ = 96;
                            for (int i = 1; i <= K; ++i) {
                                current_statement_begin__ = 97;
                                stan::model::assign(accumulator, 
                                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                            ((get_base1(get_base1(get_base1(logalpha, (t - 1), "logalpha", 1), nn, "logalpha", 2), i, "logalpha", 3) + stan::math::log(get_base1(get_base1(get_base1(A, nn_, "A", 1), i, "A", 2), j, "A", 3))) + normal_log(get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "y", 1), (((get_base1(phi, j, "phi", 1) * get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 2), "y", 1)) + multiply(get_base1(x_d_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_d_", 1), alpha)) + multiply(get_base1(x_e_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)), 
                                            "assigning variable accumulator");
                            }
                            current_statement_begin__ = 104;
                            stan::model::assign(logalpha, 
                                        stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(nn), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), 
                                        log_sum_exp(accumulator), 
                                        "assigning variable logalpha");
                            }
                        }
                    }
                    }
                }
            } else {
                current_statement_begin__ = 111;
                for (int j = 1; j <= K; ++j) {
                    {
                    current_statement_begin__ = 112;
                    validate_non_negative_index("accumulator", "K", K);
                    Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> accumulator(K);
                    stan::math::initialize(accumulator, DUMMY_VAR__);
                    stan::math::fill(accumulator, DUMMY_VAR__);
                    stan::math::assign(accumulator,stan::math::log(get_base1(pi1, 1, "pi1", 1)));
                    current_statement_begin__ = 113;
                    for (int nn = 1; nn <= N; ++nn) {
                        current_statement_begin__ = 114;
                        stan::model::assign(accumulator, 
                                    stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                                    (stan::model::rvalue(accumulator, stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), "accumulator") + normal_log(get_base1(y, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "y", 1), (multiply(get_base1(x_d_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_d_", 1), alpha) + multiply(get_base1(x_e_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)), 
                                    "assigning variable accumulator");
                    }
                    current_statement_begin__ = 118;
                    stan::model::assign(logalpha, 
                                stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                accumulator, 
                                "assigning variable logalpha");
                    }
                }
                current_statement_begin__ = 120;
                for (int t = 2; t <= T; ++t) {
                    current_statement_begin__ = 121;
                    for (int j = 1; j <= K; ++j) {
                        {
                        current_statement_begin__ = 122;
                        validate_non_negative_index("accumulator", "K", K);
                        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> accumulator(K);
                        stan::math::initialize(accumulator, DUMMY_VAR__);
                        stan::math::fill(accumulator, DUMMY_VAR__);
                        stan::math::assign(accumulator,add(get_base1(get_base1(logalpha, (t - 1), "logalpha", 1), 1, "logalpha", 2), to_vector(stan::math::log(stan::model::rvalue(A, stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), "A")))));
                        current_statement_begin__ = 123;
                        for (int nn = 1; nn <= N; ++nn) {
                            current_statement_begin__ = 124;
                            stan::math::assign(accumulator, add(accumulator, normal_log(get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "y", 1), (((get_base1(phi, j, "phi", 1) * get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 2), "y", 1)) + multiply(get_base1(x_d_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_d_", 1), alpha)) + multiply(get_base1(x_e_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)));
                        }
                        current_statement_begin__ = 129;
                        stan::model::assign(logalpha, 
                                    stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), 
                                    log_sum_exp(accumulator), 
                                    "assigning variable logalpha");
                        }
                    }
                }
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 65;
            size_t beta_j_1_max__ = Mx_e_;
            size_t beta_j_2_max__ = K;
            for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                    if (stan::math::is_uninitialized(beta(j_1__, j_2__))) {
                        std::stringstream msg__;
                        msg__ << "Undefined transformed parameter: beta" << "(" << j_1__ << ", " << j_2__ << ")";
                        stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable beta: ") + msg__.str()), current_statement_begin__, prog_reader__());
                    }
                }
            }
            current_statement_begin__ = 66;
            size_t logalpha_k_0_max__ = T;
            size_t logalpha_k_1_max__ = N_s;
            size_t logalpha_j_1_max__ = K;
            for (size_t k_0__ = 0; k_0__ < logalpha_k_0_max__; ++k_0__) {
                for (size_t k_1__ = 0; k_1__ < logalpha_k_1_max__; ++k_1__) {
                    for (size_t j_1__ = 0; j_1__ < logalpha_j_1_max__; ++j_1__) {
                        if (stan::math::is_uninitialized(logalpha[k_0__][k_1__](j_1__))) {
                            std::stringstream msg__;
                            msg__ << "Undefined transformed parameter: logalpha" << "[" << k_0__ << "]" << "[" << k_1__ << "]" << "(" << j_1__ << ")";
                            stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable logalpha: ") + msg__.str()), current_statement_begin__, prog_reader__());
                        }
                    }
                }
            }
            // model body
            current_statement_begin__ = 138;
            lp_accum__.add(normal_log(sigma, 0, 5));
            current_statement_begin__ = 141;
            lp_accum__.add(normal_log(phi, 0.5, 0.5));
            current_statement_begin__ = 144;
            for (int n = 1; n <= N_tp; ++n) {
                current_statement_begin__ = 145;
                for (int k = 1; k <= K; ++k) {
                    current_statement_begin__ = 146;
                    lp_accum__.add(dirichlet_log(get_base1(get_base1(A, n, "A", 1), k, "A", 2), rep_vector(1, K)));
                }
            }
            current_statement_begin__ = 149;
            lp_accum__.add(normal_log(alpha, 0, 2));
            current_statement_begin__ = 150;
            for (int i = 1; i <= K; ++i) {
                current_statement_begin__ = 151;
                lp_accum__.add(normal_log(stan::model::rvalue(beta_un, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), "beta_un"), 0, 2));
                current_statement_begin__ = 152;
                lp_accum__.add(normal_log(stan::model::rvalue(beta_ord, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list())), "beta_ord"), 0, 2));
            }
            current_statement_begin__ = 158;
            for (int n = 1; n <= N_s; ++n) {
                current_statement_begin__ = 159;
                lp_accum__.add(log_sum_exp(get_base1(get_base1(logalpha, T, "logalpha", 1), n, "logalpha", 2)));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("pi1");
        names__.push_back("A");
        names__.push_back("phi");
        names__.push_back("alpha");
        names__.push_back("beta_un");
        names__.push_back("beta_ord");
        names__.push_back("sigma");
        names__.push_back("beta");
        names__.push_back("logalpha");
        names__.push_back("prS");
        names__.push_back("log_lik");
        names__.push_back("yrep");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(N_s);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_tp);
        dims__.push_back(K);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mx_d_);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mx_e_un);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mx_e_ord);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(Mx_e_);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(T);
        dims__.push_back(N_s);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(T);
        dims__.push_back(N_s);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NT);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(NT);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_msm_constant_continuous_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > pi1;
        size_t pi1_d_0_max__ = N_s;
        pi1.reserve(pi1_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < pi1_d_0_max__; ++d_0__) {
            pi1.push_back(in__.simplex_constrain(K));
        }
        size_t pi1_j_1_max__ = K;
        size_t pi1_k_0_max__ = N_s;
        for (size_t j_1__ = 0; j_1__ < pi1_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < pi1_k_0_max__; ++k_0__) {
                vars__.push_back(pi1[k_0__](j_1__));
            }
        }
        std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > > A;
        size_t A_d_0_max__ = N_tp;
        size_t A_d_1_max__ = K;
        A.resize(A_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < A_d_0_max__; ++d_0__) {
            A[d_0__].reserve(A_d_1_max__);
            for (size_t d_1__ = 0; d_1__ < A_d_1_max__; ++d_1__) {
                A[d_0__].push_back(in__.simplex_constrain(K));
            }
        }
        size_t A_j_1_max__ = K;
        size_t A_k_0_max__ = N_tp;
        size_t A_k_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < A_j_1_max__; ++j_1__) {
            for (size_t k_1__ = 0; k_1__ < A_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < A_k_0_max__; ++k_0__) {
                    vars__.push_back(A[k_0__][k_1__](j_1__));
                }
            }
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> phi = in__.ordered_constrain(K);
        size_t phi_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
            vars__.push_back(phi(j_1__));
        }
        Eigen::Matrix<double, Eigen::Dynamic, 1> alpha = in__.vector_constrain(Mx_d_);
        size_t alpha_j_1_max__ = Mx_d_;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            vars__.push_back(alpha(j_1__));
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > beta_un;
        size_t beta_un_d_0_max__ = Mx_e_un;
        beta_un.reserve(beta_un_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < beta_un_d_0_max__; ++d_0__) {
            beta_un.push_back(in__.vector_constrain(K));
        }
        size_t beta_un_j_1_max__ = K;
        size_t beta_un_k_0_max__ = Mx_e_un;
        for (size_t j_1__ = 0; j_1__ < beta_un_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_un_k_0_max__; ++k_0__) {
                vars__.push_back(beta_un[k_0__](j_1__));
            }
        }
        std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > beta_ord;
        size_t beta_ord_d_0_max__ = Mx_e_ord;
        beta_ord.reserve(beta_ord_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < beta_ord_d_0_max__; ++d_0__) {
            beta_ord.push_back(in__.ordered_constrain(K));
        }
        size_t beta_ord_j_1_max__ = K;
        size_t beta_ord_k_0_max__ = Mx_e_ord;
        for (size_t j_1__ = 0; j_1__ < beta_ord_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_ord_k_0_max__; ++k_0__) {
                vars__.push_back(beta_ord[k_0__](j_1__));
            }
        }
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 65;
            validate_non_negative_index("beta", "Mx_e_", Mx_e_);
            validate_non_negative_index("beta", "K", K);
            Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic> beta(Mx_e_, K);
            stan::math::initialize(beta, DUMMY_VAR__);
            stan::math::fill(beta, DUMMY_VAR__);
            current_statement_begin__ = 66;
            validate_non_negative_index("logalpha", "K", K);
            validate_non_negative_index("logalpha", "T", T);
            validate_non_negative_index("logalpha", "N_s", N_s);
            std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > > logalpha(T, std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(N_s, Eigen::Matrix<double, Eigen::Dynamic, 1>(K)));
            stan::math::initialize(logalpha, DUMMY_VAR__);
            stan::math::fill(logalpha, DUMMY_VAR__);
            // do transformed parameters statements
            {
            current_statement_begin__ = 69;
            int count_ordered(0);
            (void) count_ordered;  // dummy to suppress unused var warning
            stan::math::fill(count_ordered, std::numeric_limits<int>::min());
            stan::math::assign(count_ordered,1);
            current_statement_begin__ = 70;
            int count_unordered(0);
            (void) count_unordered;  // dummy to suppress unused var warning
            stan::math::fill(count_unordered, std::numeric_limits<int>::min());
            stan::math::assign(count_unordered,1);
            current_statement_begin__ = 71;
            for (int m = 1; m <= Mx_e_; ++m) {
                current_statement_begin__ = 72;
                if (as_bool(get_base1(order_x_e, m, "order_x_e", 1))) {
                    current_statement_begin__ = 73;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(m), stan::model::nil_index_list()), 
                                transpose(get_base1(beta_ord, count_ordered, "beta_ord", 1)), 
                                "assigning variable beta");
                    current_statement_begin__ = 73;
                    stan::math::assign(count_ordered, (count_ordered + 1));
                } else {
                    current_statement_begin__ = 75;
                    stan::model::assign(beta, 
                                stan::model::cons_list(stan::model::index_uni(m), stan::model::nil_index_list()), 
                                transpose(get_base1(beta_un, count_unordered, "beta_un", 1)), 
                                "assigning variable beta");
                    current_statement_begin__ = 75;
                    stan::math::assign(count_unordered, (count_unordered + 1));
                }
            }
            }
            current_statement_begin__ = 79;
            if (as_bool(logical_eq(shared_S, 0))) {
                current_statement_begin__ = 86;
                for (int nn = 1; nn <= N; ++nn) {
                    {
                    current_statement_begin__ = 87;
                    int nn_(0);
                    (void) nn_;  // dummy to suppress unused var warning
                    stan::math::fill(nn_, std::numeric_limits<int>::min());
                    stan::math::assign(nn_,(shared_TP ? 1 : nn ));
                    current_statement_begin__ = 88;
                    for (int j = 1; j <= K; ++j) {
                        current_statement_begin__ = 89;
                        stan::model::assign(logalpha, 
                                    stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(nn), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), 
                                    (stan::math::log(get_base1(get_base1(pi1, nn, "pi1", 1), j, "pi1", 2)) + normal_log(get_base1(y, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "y", 1), (multiply(get_base1(x_d_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_d_", 1), alpha) + multiply(get_base1(x_e_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)), 
                                    "assigning variable logalpha");
                    }
                    current_statement_begin__ = 93;
                    for (int t = 2; t <= T; ++t) {
                        current_statement_begin__ = 94;
                        for (int j = 1; j <= K; ++j) {
                            {
                            current_statement_begin__ = 95;
                            validate_non_negative_index("accumulator", "K", K);
                            std::vector<local_scalar_t__  > accumulator(K, local_scalar_t__(DUMMY_VAR__));
                            stan::math::initialize(accumulator, DUMMY_VAR__);
                            stan::math::fill(accumulator, DUMMY_VAR__);
                            current_statement_begin__ = 96;
                            for (int i = 1; i <= K; ++i) {
                                current_statement_begin__ = 97;
                                stan::model::assign(accumulator, 
                                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                            ((get_base1(get_base1(get_base1(logalpha, (t - 1), "logalpha", 1), nn, "logalpha", 2), i, "logalpha", 3) + stan::math::log(get_base1(get_base1(get_base1(A, nn_, "A", 1), i, "A", 2), j, "A", 3))) + normal_log(get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "y", 1), (((get_base1(phi, j, "phi", 1) * get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 2), "y", 1)) + multiply(get_base1(x_d_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_d_", 1), alpha)) + multiply(get_base1(x_e_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)), 
                                            "assigning variable accumulator");
                            }
                            current_statement_begin__ = 104;
                            stan::model::assign(logalpha, 
                                        stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(nn), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), 
                                        log_sum_exp(accumulator), 
                                        "assigning variable logalpha");
                            }
                        }
                    }
                    }
                }
            } else {
                current_statement_begin__ = 111;
                for (int j = 1; j <= K; ++j) {
                    {
                    current_statement_begin__ = 112;
                    validate_non_negative_index("accumulator", "K", K);
                    Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> accumulator(K);
                    stan::math::initialize(accumulator, DUMMY_VAR__);
                    stan::math::fill(accumulator, DUMMY_VAR__);
                    stan::math::assign(accumulator,stan::math::log(get_base1(pi1, 1, "pi1", 1)));
                    current_statement_begin__ = 113;
                    for (int nn = 1; nn <= N; ++nn) {
                        current_statement_begin__ = 114;
                        stan::model::assign(accumulator, 
                                    stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), 
                                    (stan::model::rvalue(accumulator, stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()), "accumulator") + normal_log(get_base1(y, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "y", 1), (multiply(get_base1(x_d_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_d_", 1), alpha) + multiply(get_base1(x_e_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)), 
                                    "assigning variable accumulator");
                    }
                    current_statement_begin__ = 118;
                    stan::model::assign(logalpha, 
                                stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list())), 
                                accumulator, 
                                "assigning variable logalpha");
                    }
                }
                current_statement_begin__ = 120;
                for (int t = 2; t <= T; ++t) {
                    current_statement_begin__ = 121;
                    for (int j = 1; j <= K; ++j) {
                        {
                        current_statement_begin__ = 122;
                        validate_non_negative_index("accumulator", "K", K);
                        Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> accumulator(K);
                        stan::math::initialize(accumulator, DUMMY_VAR__);
                        stan::math::fill(accumulator, DUMMY_VAR__);
                        stan::math::assign(accumulator,add(get_base1(get_base1(logalpha, (t - 1), "logalpha", 1), 1, "logalpha", 2), to_vector(stan::math::log(stan::model::rvalue(A, stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), "A")))));
                        current_statement_begin__ = 123;
                        for (int nn = 1; nn <= N; ++nn) {
                            current_statement_begin__ = 124;
                            stan::math::assign(accumulator, add(accumulator, normal_log(get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "y", 1), (((get_base1(phi, j, "phi", 1) * get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 2), "y", 1)) + multiply(get_base1(x_d_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_d_", 1), alpha)) + multiply(get_base1(x_e_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_e_", 1), stan::model::rvalue(beta, stan::model::cons_list(stan::model::index_omni(), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list())), "beta"))), sigma)));
                        }
                        current_statement_begin__ = 129;
                        stan::model::assign(logalpha, 
                                    stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(1), stan::model::cons_list(stan::model::index_uni(j), stan::model::nil_index_list()))), 
                                    log_sum_exp(accumulator), 
                                    "assigning variable logalpha");
                        }
                    }
                }
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t beta_j_2_max__ = K;
                size_t beta_j_1_max__ = Mx_e_;
                for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                    for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                        vars__.push_back(beta(j_1__, j_2__));
                    }
                }
                size_t logalpha_j_1_max__ = K;
                size_t logalpha_k_0_max__ = T;
                size_t logalpha_k_1_max__ = N_s;
                for (size_t j_1__ = 0; j_1__ < logalpha_j_1_max__; ++j_1__) {
                    for (size_t k_1__ = 0; k_1__ < logalpha_k_1_max__; ++k_1__) {
                        for (size_t k_0__ = 0; k_0__ < logalpha_k_0_max__; ++k_0__) {
                            vars__.push_back(logalpha[k_0__][k_1__](j_1__));
                        }
                    }
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 165;
            validate_non_negative_index("prS", "K", K);
            validate_non_negative_index("prS", "T", T);
            validate_non_negative_index("prS", "N_s", N_s);
            std::vector<std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> > > prS(T, std::vector<Eigen::Matrix<double, Eigen::Dynamic, 1> >(N_s, Eigen::Matrix<double, Eigen::Dynamic, 1>(K)));
            stan::math::initialize(prS, DUMMY_VAR__);
            stan::math::fill(prS, DUMMY_VAR__);
            current_statement_begin__ = 166;
            validate_non_negative_index("log_lik", "NT", NT);
            std::vector<double> log_lik(NT, double(0));
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            current_statement_begin__ = 167;
            validate_non_negative_index("yrep", "NT", NT);
            std::vector<double> yrep(NT, double(0));
            stan::math::initialize(yrep, DUMMY_VAR__);
            stan::math::fill(yrep, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 170;
            for (int n = 1; n <= N; ++n) {
                {
                current_statement_begin__ = 171;
                int n_(0);
                (void) n_;  // dummy to suppress unused var warning
                stan::math::fill(n_, std::numeric_limits<int>::min());
                stan::math::assign(n_,(shared_S ? 1 : n ));
                current_statement_begin__ = 172;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 173;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(((get_base1(get_base1(startstop, n, "startstop", 1), 1, "startstop", 2) + t) - 1)), stan::model::nil_index_list()), 
                                log_sum_exp(get_base1(get_base1(logalpha, t, "logalpha", 1), n_, "logalpha", 2)), 
                                "assigning variable log_lik");
                }
                }
            }
            current_statement_begin__ = 178;
            for (int n = 1; n <= N_s; ++n) {
                current_statement_begin__ = 179;
                for (int t = 1; t <= T; ++t) {
                    current_statement_begin__ = 180;
                    stan::model::assign(prS, 
                                stan::model::cons_list(stan::model::index_uni(t), stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list())), 
                                softmax(get_base1(get_base1(logalpha, t, "logalpha", 1), n, "logalpha", 2)), 
                                "assigning variable prS");
                }
            }
            current_statement_begin__ = 185;
            for (int nn = 1; nn <= N; ++nn) {
                {
                current_statement_begin__ = 186;
                int nn_(0);
                (void) nn_;  // dummy to suppress unused var warning
                stan::math::fill(nn_, std::numeric_limits<int>::min());
                stan::math::assign(nn_,(shared_S ? 1 : nn ));
                current_statement_begin__ = 187;
                stan::model::assign(yrep, 
                            stan::model::cons_list(stan::model::index_uni(get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2)), stan::model::nil_index_list()), 
                            sum(elt_multiply(get_base1(get_base1(prS, 1, "prS", 1), nn_, "prS", 2), to_vector(normal_rng(add(multiply(get_base1(x_d_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_d_", 1), alpha), to_vector(multiply(get_base1(x_e_, get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2), "x_e_", 1), beta))), sigma, base_rng__)))), 
                            "assigning variable yrep");
                current_statement_begin__ = 190;
                for (int t = 2; t <= T; ++t) {
                    current_statement_begin__ = 191;
                    stan::model::assign(yrep, 
                                stan::model::cons_list(stan::model::index_uni(((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1)), stan::model::nil_index_list()), 
                                sum(elt_multiply(get_base1(get_base1(prS, t, "prS", 1), nn_, "prS", 2), to_vector(normal_rng(add(add(multiply(phi, get_base1(y, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 2), "y", 1)), multiply(stan::model::rvalue(x_d_, stan::model::cons_list(stan::model::index_uni(((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1)), stan::model::cons_list(stan::model::index_omni(), stan::model::nil_index_list())), "x_d_"), alpha)), to_vector(multiply(get_base1(x_e_, ((get_base1(get_base1(startstop, nn, "startstop", 1), 1, "startstop", 2) + t) - 1), "x_e_", 1), beta))), sigma, base_rng__)))), 
                                "assigning variable yrep");
                }
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 165;
            size_t prS_j_1_max__ = K;
            size_t prS_k_0_max__ = T;
            size_t prS_k_1_max__ = N_s;
            for (size_t j_1__ = 0; j_1__ < prS_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < prS_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < prS_k_0_max__; ++k_0__) {
                        vars__.push_back(prS[k_0__][k_1__](j_1__));
                    }
                }
            }
            current_statement_begin__ = 166;
            size_t log_lik_k_0_max__ = NT;
            for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
                vars__.push_back(log_lik[k_0__]);
            }
            current_statement_begin__ = 167;
            size_t yrep_k_0_max__ = NT;
            for (size_t k_0__ = 0; k_0__ < yrep_k_0_max__; ++k_0__) {
                vars__.push_back(yrep[k_0__]);
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_msm_constant_continuous";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t pi1_j_1_max__ = K;
        size_t pi1_k_0_max__ = N_s;
        for (size_t j_1__ = 0; j_1__ < pi1_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < pi1_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "pi1" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t A_j_1_max__ = K;
        size_t A_k_0_max__ = N_tp;
        size_t A_k_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < A_j_1_max__; ++j_1__) {
            for (size_t k_1__ = 0; k_1__ < A_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < A_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "A" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t phi_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_j_1_max__ = Mx_d_;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_un_j_1_max__ = K;
        size_t beta_un_k_0_max__ = Mx_e_un;
        for (size_t j_1__ = 0; j_1__ < beta_un_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_un_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_un" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_ord_j_1_max__ = K;
        size_t beta_ord_k_0_max__ = Mx_e_ord;
        for (size_t j_1__ = 0; j_1__ < beta_ord_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_ord_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_ord" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t beta_j_2_max__ = K;
            size_t beta_j_1_max__ = Mx_e_;
            for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "beta" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t logalpha_j_1_max__ = K;
            size_t logalpha_k_0_max__ = T;
            size_t logalpha_k_1_max__ = N_s;
            for (size_t j_1__ = 0; j_1__ < logalpha_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < logalpha_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < logalpha_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "logalpha" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
        }
        if (!include_gqs__) return;
        size_t prS_j_1_max__ = K;
        size_t prS_k_0_max__ = T;
        size_t prS_k_1_max__ = N_s;
        for (size_t j_1__ = 0; j_1__ < prS_j_1_max__; ++j_1__) {
            for (size_t k_1__ = 0; k_1__ < prS_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < prS_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "prS" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t log_lik_k_0_max__ = NT;
        for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t yrep_k_0_max__ = NT;
        for (size_t k_0__ = 0; k_0__ < yrep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "yrep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t pi1_j_1_max__ = (K - 1);
        size_t pi1_k_0_max__ = N_s;
        for (size_t j_1__ = 0; j_1__ < pi1_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < pi1_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "pi1" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t A_j_1_max__ = (K - 1);
        size_t A_k_0_max__ = N_tp;
        size_t A_k_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < A_j_1_max__; ++j_1__) {
            for (size_t k_1__ = 0; k_1__ < A_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < A_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "A" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t phi_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < phi_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "phi" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t alpha_j_1_max__ = Mx_d_;
        for (size_t j_1__ = 0; j_1__ < alpha_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "alpha" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t beta_un_j_1_max__ = K;
        size_t beta_un_k_0_max__ = Mx_e_un;
        for (size_t j_1__ = 0; j_1__ < beta_un_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_un_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_un" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        size_t beta_ord_j_1_max__ = K;
        size_t beta_ord_k_0_max__ = Mx_e_ord;
        for (size_t j_1__ = 0; j_1__ < beta_ord_j_1_max__; ++j_1__) {
            for (size_t k_0__ = 0; k_0__ < beta_ord_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "beta_ord" << '.' << k_0__ + 1 << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t beta_j_2_max__ = K;
            size_t beta_j_1_max__ = Mx_e_;
            for (size_t j_2__ = 0; j_2__ < beta_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "beta" << '.' << j_1__ + 1 << '.' << j_2__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
            size_t logalpha_j_1_max__ = K;
            size_t logalpha_k_0_max__ = T;
            size_t logalpha_k_1_max__ = N_s;
            for (size_t j_1__ = 0; j_1__ < logalpha_j_1_max__; ++j_1__) {
                for (size_t k_1__ = 0; k_1__ < logalpha_k_1_max__; ++k_1__) {
                    for (size_t k_0__ = 0; k_0__ < logalpha_k_0_max__; ++k_0__) {
                        param_name_stream__.str(std::string());
                        param_name_stream__ << "logalpha" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                        param_names__.push_back(param_name_stream__.str());
                    }
                }
            }
        }
        if (!include_gqs__) return;
        size_t prS_j_1_max__ = K;
        size_t prS_k_0_max__ = T;
        size_t prS_k_1_max__ = N_s;
        for (size_t j_1__ = 0; j_1__ < prS_j_1_max__; ++j_1__) {
            for (size_t k_1__ = 0; k_1__ < prS_k_1_max__; ++k_1__) {
                for (size_t k_0__ = 0; k_0__ < prS_k_0_max__; ++k_0__) {
                    param_name_stream__.str(std::string());
                    param_name_stream__ << "prS" << '.' << k_0__ + 1 << '.' << k_1__ + 1 << '.' << j_1__ + 1;
                    param_names__.push_back(param_name_stream__.str());
                }
            }
        }
        size_t log_lik_k_0_max__ = NT;
        for (size_t k_0__ = 0; k_0__ < log_lik_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t yrep_k_0_max__ = NT;
        for (size_t k_0__ = 0; k_0__ < yrep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "yrep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_msm_constant_continuous_namespace::model_msm_constant_continuous stan_model;
#endif
